version: "3.0"

networks:
    api_tg_network:
        name: api_tg_network

services:
    php-apache:
        image: webdevops/php-apache-dev:8.2-alpine
        container_name: api-back-tg
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/app
        environment:
            WEB_DOCUMENT_ROOT: /app/public
        networks:
            api_tg_network:
                aliases:
                    - api-back
